/**
 * @file src/features/local-tts/offscreen/tts.worker.ts
 * 文件职责：在独立 Worker 中加载并运行 Kokoro v1.1 中文 TTS，避免推理阻塞 Offscreen DOM。
 * 主要内容：固定模型版本、WebGPU/WASM 回退、串行合成、句段流式生成和 WAV 编码。
 * 模块边界：只运行本地模型，不访问配置、网页、标签页或直接播放 Audio。
 */

import {KokoroTTS, env as kokoroEnv} from '@uzen/kokoro-js';
import {env as kokoroTransformersEnv} from '@huggingface/transformers-kokoro';
import {
    LOCAL_TTS_MODEL_DTYPE,
    LOCAL_TTS_MODEL_FILE_NAME,
    LOCAL_TTS_MODEL_REPOSITORY,
    LOCAL_TTS_MODEL_REVISION,
    LOCAL_TTS_VOICE_PATH,
} from '@/src/core/config/localTts';

type LocalTtsDevice = 'webgpu' | 'wasm';

interface WorkerRequest {
    requestId: number;
    type: 'prepare' | 'synthesize' | 'dispose';
    text?: string;
    voice?: string;
    speed?: number;
}

interface WorkerResponse {
    requestId: number;
    success: boolean;
    audio?: ArrayBuffer;
    samplingRate?: number;
    backend?: LocalTtsDevice;
    error?: string;
}

let modelPromise: Promise<KokoroTTS> | null = null;
let modelBackend: LocalTtsDevice | undefined;
let taskQueue: Promise<void> = Promise.resolve();
let fetchPatched = false;

function errorMessage(error: unknown): string {
    return error instanceof Error ? error.message : String(error);
}

function extensionUrl(path: string): string {
    const getUrl = (globalThis as typeof globalThis & {
        chrome?: {runtime?: {getURL?: (value: string) => string}};
    }).chrome?.runtime?.getURL;
    return getUrl?.(path) || new URL(path, self.location.href).toString();
}

function requestUrl(input: RequestInfo | URL): string {
    return typeof input === 'string'
        ? input
        : input instanceof URL
            ? input.toString()
            : input.url;
}

function modelCacheUrls(url: string): string[] {
    const mainPrefix = `/${LOCAL_TTS_MODEL_REPOSITORY}/resolve/main/`;
    const pinnedPrefix = `/${LOCAL_TTS_MODEL_REPOSITORY}/resolve/${LOCAL_TTS_MODEL_REVISION}/`;
    if (url.includes(mainPrefix)) return [url, url.replace(mainPrefix, pinnedPrefix)];
    if (url.includes(pinnedPrefix)) return [url, url.replace(pinnedPrefix, mainPrefix)];
    return [url];
}

async function localCacheFetch(
    input: RequestInfo | URL,
    init: RequestInit | undefined,
    nativeFetch: typeof fetch,
): Promise<Response> {
    const url = requestUrl(input);
    const isModelFile = url.includes(`/${LOCAL_TTS_MODEL_REPOSITORY}/resolve/`);
    const isVoiceFile = url.startsWith(`${LOCAL_TTS_VOICE_PATH}/`);
    if (!isModelFile && !isVoiceFile) return nativeFetch(input, init);
    if (typeof caches === 'undefined') throw new Error('本地 TTS 缓存不可用');

    const cache = await caches.open(isVoiceFile ? 'kokoro-voices' : 'transformers-cache');
    for (const cacheUrl of isModelFile ? modelCacheUrls(url) : [url]) {
        const cached = await cache.match(cacheUrl);
        if (cached) return cached;
    }
    throw new Error(`本地 TTS 缓存缺少模型文件：${url}`);
}

/** @remarks @uzen/kokoro-js 没有 revision 参数；模型 URL 只允许读取固定版本的本地缓存。 */
function installLocalOnlyFetch(): void {
    if (fetchPatched) return;
    fetchPatched = true;
    const nativeFetch = globalThis.fetch.bind(globalThis);
    const offlineFetch = (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => localCacheFetch(input, init, nativeFetch);
    globalThis.fetch = offlineFetch as typeof fetch;
    kokoroTransformersEnv.fetch = offlineFetch;
}

function configureRuntime(): void {
    installLocalOnlyFetch();
    kokoroEnv.allowLocalModels = false;
    kokoroTransformersEnv.allowLocalModels = false;
    // Transformers.js uses the remote model namespace as the Cache Storage key;
    // offlineFetch above prevents a cache miss from reaching the network.
    kokoroTransformersEnv.allowRemoteModels = true;
    kokoroTransformersEnv.useBrowserCache = true;
    // MV3 extension CSP rejects the blob URL generated by the WASM factory
    // pre-cache path; load the static extension-owned JSEP files directly.
    kokoroTransformersEnv.useWasmCache = false;
    if (kokoroTransformersEnv.backends.onnx.wasm) {
        kokoroTransformersEnv.backends.onnx.wasm.numThreads = 1;
        kokoroTransformersEnv.backends.onnx.wasm.proxy = false;
        kokoroTransformersEnv.backends.onnx.wasm.wasmPaths = {
            mjs: extensionUrl('fluent-read-ai/tts-ort-wasm-simd-threaded.jsep.mjs'),
            wasm: extensionUrl('fluent-read-ai/tts-ort-wasm-simd-threaded.jsep.wasm'),
        };
    }
    kokoroEnv.wasmPaths = {
        mjs: extensionUrl('fluent-read-ai/tts-ort-wasm-simd-threaded.jsep.mjs'),
        wasm: extensionUrl('fluent-read-ai/tts-ort-wasm-simd-threaded.jsep.wasm'),
    };
}

async function createModel(device: LocalTtsDevice): Promise<KokoroTTS> {
    configureRuntime();
    return KokoroTTS.from_pretrained(LOCAL_TTS_MODEL_REPOSITORY, {
        dtype: LOCAL_TTS_MODEL_DTYPE,
        device,
        model_file_name: LOCAL_TTS_MODEL_FILE_NAME,
        voicePath: LOCAL_TTS_VOICE_PATH,
    });
}

async function getModel(): Promise<KokoroTTS> {
    if (modelPromise) return modelPromise;
    // 扩展 CSP 下 WebGPU 的动态模块加载在部分 Edge 版本会失败；WASM 是
    // 首版的稳定路径，保留 device 类型以便后续经过真实扩展验证后切换。
    const preferred: LocalTtsDevice = 'wasm';
    modelPromise = createModel(preferred)
        .then((model) => {
            modelBackend = preferred;
            return model;
        })
        .catch((error) => {
            modelPromise = null;
            modelBackend = undefined;
            throw error;
        });
    return modelPromise;
}

function concatAudio(chunks: readonly Float32Array[]): Float32Array {
    const total = chunks.reduce((size, chunk) => size + chunk.length, 0);
    const output = new Float32Array(total);
    let offset = 0;
    for (const chunk of chunks) {
        output.set(chunk, offset);
        offset += chunk.length;
    }
    return output;
}

function floatToPcm16(value: number): number {
    const clamped = Math.max(-1, Math.min(1, value));
    return clamped < 0 ? Math.round(clamped * 0x8000) : Math.round(clamped * 0x7fff);
}

function encodeWav(samples: Float32Array, sampleRate: number): ArrayBuffer {
    const dataLength = samples.length * 2;
    const buffer = new ArrayBuffer(44 + dataLength);
    const view = new DataView(buffer);
    const writeAscii = (offset: number, value: string) => {
        for (let index = 0; index < value.length; index += 1) view.setUint8(offset + index, value.charCodeAt(index));
    };
    writeAscii(0, 'RIFF');
    view.setUint32(4, 36 + dataLength, true);
    writeAscii(8, 'WAVE');
    writeAscii(12, 'fmt ');
    view.setUint32(16, 16, true);
    view.setUint16(20, 1, true);
    view.setUint16(22, 1, true);
    view.setUint32(24, sampleRate, true);
    view.setUint32(28, sampleRate * 2, true);
    view.setUint16(32, 2, true);
    view.setUint16(34, 16, true);
    writeAscii(36, 'data');
    view.setUint32(40, dataLength, true);
    for (let index = 0; index < samples.length; index += 1) view.setInt16(44 + index * 2, floatToPcm16(samples[index]), true);
    return buffer;
}

async function synthesize(request: WorkerRequest): Promise<{audio: ArrayBuffer; samplingRate: number}> {
    const text = request.text?.trim() || '';
    if (!text) throw new Error('本地 TTS 文本为空');
    const voice = request.voice?.trim() || 'zf_001';
    const speed = typeof request.speed === 'number' && Number.isFinite(request.speed)
        ? Math.min(2, Math.max(0.5, request.speed))
        : 1;
    const model = await getModel();
    const chunks: Float32Array[] = [];
    let samplingRate = 24_000;
    for await (const item of model.stream(text, {voice: voice as never, speed, maxChunkLength: 180})) {
        const samples = item.audio.audio;
        chunks.push(samples instanceof Float32Array ? samples.slice() : concatAudio(samples));
        samplingRate = item.audio.sampling_rate;
    }
    return {audio: encodeWav(concatAudio(chunks), samplingRate), samplingRate};
}

async function disposeModel(): Promise<void> {
    const current = modelPromise;
    modelPromise = null;
    modelBackend = undefined;
    if (!current) return;
    try {
        const model = await current;
        await (model.model as unknown as {dispose?: () => Promise<void> | void}).dispose?.();
    } catch {
        // Worker termination remains the final resource boundary.
    }
}

function enqueue<T>(operation: () => Promise<T>): Promise<T> {
    const run = taskQueue.then(operation, operation);
    taskQueue = run.then(() => undefined, () => undefined);
    return run;
}

function post(response: WorkerResponse): void {
    const workerScope = self as unknown as {postMessage(message: unknown, transfer?: Transferable[]): void};
    if (response.audio) workerScope.postMessage(response, [response.audio]);
    else workerScope.postMessage(response);
}

async function handle(request: WorkerRequest): Promise<void> {
    try {
        if (request.type === 'dispose') {
            await disposeModel();
            post({requestId: request.requestId, success: true});
            return;
        }
        if (request.type === 'prepare') {
            await getModel();
            post({requestId: request.requestId, success: true, backend: modelBackend});
            return;
        }
        const result = await synthesize(request);
        post({
            requestId: request.requestId,
            success: true,
            audio: result.audio,
            samplingRate: result.samplingRate,
            backend: modelBackend,
        });
    } catch (error) {
        post({requestId: request.requestId, success: false, error: errorMessage(error)});
    }
}

export function startLocalTtsWorker(): void {
    self.onmessage = (event: MessageEvent<WorkerRequest>) => {
        const request = event.data;
        if (!request || typeof request.requestId !== 'number' || !['prepare', 'synthesize', 'dispose'].includes(request.type)) return;
        void enqueue(() => handle(request));
    };
}
