import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

function source(path: string): string {
  return readFileSync(resolve(process.cwd(), path), 'utf8')
}

function sourceBody(path: string): string {
  const content = source(path)
  const header = content.match(/^\/\*\*[\s\S]*?\*\/\s*/u)?.[0]
  return header?.includes('@file ' + path) ? content.slice(header.length) : content
}

function sectionAt(content: string, sectionStart: number): string {
  const sectionTags = /<\/?section\b[^>]*>/gu
  sectionTags.lastIndex = sectionStart
  let depth = 0
  let match: RegExpExecArray | null
  while ((match = sectionTags.exec(content))) {
    depth += match[0].startsWith('</') ? -1 : 1
    if (depth === 0) return content.slice(sectionStart, sectionTags.lastIndex)
  }
  throw new Error(`Missing closing section at offset ${sectionStart}`)
}

function activeSectionSource(content: string, id: string): string {
  const openingSections = /<section\b[^>]*>/gu
  const sections: string[] = []
  let match: RegExpExecArray | null
  while ((match = openingSections.exec(content))) {
    if (match[0].includes(`props.activeSection === '${id}'`)) {
      sections.push(sectionAt(content, match.index))
    }
  }
  if (!sections.length) throw new Error(`Missing active section ${id}`)
  return sections.join('\n')
}

function settingsGroupTitles(content: string): string[] {
  return [...content.matchAll(/<SettingsGroup\b[^>]*\btitle="([^"]+)"/gu)]
    .map((match) => match[1])
}

describe('options UI composition architecture', () => {
  it('keeps the WXT options entrypoint as a thin app composition shell', () => {
    const entrypoint = sourceBody('entrypoints/options/main.ts')
    expect(entrypoint).toBe("import { mountOptionsApp } from '@/src/app/options'\n\nmountOptionsApp('#app')\n")
  })

  it('keeps the WXT popup entrypoint as a thin app composition shell', () => {
    const entrypoint = sourceBody('entrypoints/popup/main.ts')
    expect(entrypoint).toBe("import {mountPopupApp} from '@/src/app/popup';\n\nmountPopupApp('#app');\n")
  })

  it('owns settings, feature UI and shared components in their target layers', () => {
    const optionsApp = source('src/app/options/OptionsApp.vue')
    const settingsSections = source('src/features/settings/ui/SettingsSections.vue')
    const interfaceSettings = source('src/features/settings/ui/InterfaceSettings.vue')
    const interfaceSkinPreview = source('src/features/settings/ui/components/InterfaceSkinPreview.vue')
    const settingsItem = source('src/features/settings/ui/components/SettingsItem.vue')
    const popupLayoutEditor = source('src/features/settings/ui/PopupLayoutEditor.vue')
    const popupSiteRule = source('src/app/popup/PopupSiteRule.vue')
    const popupEntry = source('src/app/popup/index.ts')
    const optionsEntry = source('src/app/options/index.ts')
    const skinStyles = source('src/ui/styles/interface-skins.css')
    const minimalSkinStyles = source('src/ui/styles/interface-skins/minimal.css')
    const paletteSkinStyles = source('src/ui/styles/interface-skins/palette.css')
    const interfaceAppearance = source('src/ui/interfaceAppearance.ts')
    const popupHtml = source('entrypoints/popup/index.html')
    const configManagement = source('src/features/settings/ui/ConfigManagement.vue')
    const localDataManagement = source('src/features/settings/ui/LocalDataManagement.vue')
    const serviceConfiguration = source('src/features/settings/ui/services/ServiceConfiguration.vue')
    const popup = source('src/app/popup/PopupApp.vue')
    const popupStyles = source('src/app/popup/popup.css')
    const imageSettings = source('src/features/image-translation/ui/ImageOcrSettings.vue')
    const imagePublic = source('src/features/image-translation/public.ts')
    const modelUsageDashboard = source('src/features/model-usage/ui/ModelUsageDashboard.vue')
    const modelUsagePublic = source('src/features/model-usage/public.ts')
    const quickTranslationProfiles = source('src/features/settings/ui/QuickTranslationProfiles.vue')
    const translationShortcutSettings = source('src/features/settings/ui/useTranslationShortcutSettings.ts')
    const customHotkeyInput = source('src/ui/components/CustomHotkeyInput.vue')

    expect(optionsApp).toContain("@/src/features/settings/ui/SettingsSections.vue")
    expect(optionsApp).toContain("@/src/features/vocabulary/ui/VocabularyBook.vue")
    expect(settingsSections).not.toContain('@/entrypoints/')
    expect(settingsSections).toContain('<style scoped src="./settings-sections.css"></style>')
    expect(settingsSections).toContain('<InterfaceSettings :config="config" />')
    expect(settingsSections).toContain('data-config-field="to"')
    expect(activeSectionSource(settingsSections, 'settings-general')).toContain('<InterfaceSettings :config="config" />')
    expect(settingsSections).not.toContain("props.activeSection === 'settings-interface'")
    expect(settingsSections.indexOf('<InterfaceSettings :config="config" />'))
      .toBeGreaterThan(settingsSections.indexOf('title="网页辅助"'))
    expect(interfaceSettings).toContain('interfaceSkinOptions')
    expect(interfaceSettings).toContain('interfaceSkinGroups')
    expect(interfaceSettings).toContain('groupedSkinOptions')
    expect(interfaceSettings).toContain('PopupLayoutEditor')
    expect(interfaceSettings).toContain(':order="props.config.popupModuleOrder"')
    expect(interfaceSettings).toContain(':order="props.config.popupQuickFeatureOrder"')
    expect(interfaceSettings).toContain('@update:visibility="setPopupModuleVisibility"')
    expect(interfaceSettings).toContain('withInterfaceVisibility(')
    expect(interfaceSettings).toContain('withPopupQuickFeatureVisibility(')
    expect(interfaceSettings).toContain('popupModuleOptions.map')
    expect(interfaceSettings).toContain('popupQuickFeatureOptions.map')
    expect(interfaceSettings).toContain('class="interface-skin-option"')
    expect(interfaceSettings).toContain('<template #copy>')
    expect(interfaceSettings).toContain('<InterfaceSkinPreview')
    expect(interfaceSettings).toContain('selectedSkinOption')
    expect(interfaceSettings).toContain(':aria-label="translateLegacy(\'弹窗风格\')"')
    expect(interfaceSettings).toContain('const {t, translateLegacy} = useUiI18n()')
    expect(settingsItem).toContain('<slot name="copy">')
    expect(interfaceSkinPreview).toContain('class="interface-skin-live-preview"')
    expect(interfaceSkinPreview).toContain(':data-preview-skin="skin.value"')
    expect(interfaceSkinPreview).toContain('class="preview-language-pair"')
    expect(interfaceSkinPreview).toContain('class="preview-service"')
    expect(interfaceSkinPreview).not.toContain('<img')
    expect(interfaceSettings).toContain("t('settings.interface.popupLayout.label')")
    expect(interfaceSettings).toContain("t('settings.interface.popupQuickFeatures.label')")
    expect(popupLayoutEditor).toContain('data-popup-layout-editor')
    expect(popupLayoutEditor).toContain('data-popup-quick-feature-editor')
    expect(popupLayoutEditor).toContain('data-popup-quick-feature-layout')
    expect(popupLayoutEditor).toContain('draggable="true"')
    expect(popupLayoutEditor).toContain('@keydown.up.prevent')
    expect(popupLayoutEditor).toContain('@keydown.down.prevent')
    expect(popupLayoutEditor).toContain("import {useUiI18n} from '@/src/ui/i18n'")
    expect(popupLayoutEditor).toContain('`${props.copyPrefix}.${suffix}`')
    expect(popupSiteRule).toContain('data-popup-module="siteRule"')
    expect(popupEntry).toContain("@/src/ui/styles/interface-skins.css")
    expect(optionsEntry).toContain("@/src/ui/styles/interface-skins.css")
    expect(popupHtml).toContain('class="popup-page"')
    expect(skinStyles).toContain('body.popup-page')
    expect(skinStyles).toContain('data-popup-height="content"')
    expect(skinStyles).toContain('min-height: 0')
    const nonDefaultSkins = ['minimal', 'compact', 'contrast', 'cheese', 'ocean', 'matcha', 'sakura', 'midnight', 'paper']
    for (const skin of nonDefaultSkins) {
      expect(skinStyles).toContain(`./interface-skins/${skin}.css`)
      expect(source(`src/ui/styles/interface-skins/${skin}.css`)).toContain(`data-interface-skin="${skin}"`)
    }
    expect(skinStyles).toContain('./interface-skins/palette.css')
    expect(skinStyles).not.toContain('./interface-skins/plain.css')
    expect(skinStyles).not.toContain('./interface-skins/soft.css')
    expect(minimalSkinStyles).toContain('data-interface-skin="minimal"')
    expect(minimalSkinStyles).toContain('overflow-wrap: anywhere')
    expect(minimalSkinStyles).toMatch(/\.beta-badge\s*\{\s*display: none;/u)
    expect(minimalSkinStyles).toContain('opacity: .78')
    expect(minimalSkinStyles).not.toContain('saturate(')
    expect(minimalSkinStyles).toContain('background: color-mix(in srgb, var(--brand) 16%, var(--surface-soft))')
    expect(minimalSkinStyles).toContain('background: color-mix(in srgb, var(--brand) 5%, var(--surface-soft))')
    expect(minimalSkinStyles).toContain('.translate-button.translated .translate-hotkey')
    expect(paletteSkinStyles).toContain('data-interface-skin-kind="palette"')
    expect(paletteSkinStyles).toContain('.settings-card .service-catalog')
    expect(paletteSkinStyles).toContain('.image-ocr-recommendation')
    expect(paletteSkinStyles).toContain('.settings-card.vocabulary-view .vocabulary-book')
    expect(paletteSkinStyles).toContain('--el-bg-color: var(--surface)')
    expect(interfaceAppearance).toContain('dataset.interfaceSkinKind = skin.kind')
    expect(interfaceAppearance).toContain("style.setProperty('--interface-popup-width'")
    expect(settingsSections).toContain('<ImageOcrSettings />')
    expect(settingsSections).toContain("import {ModelUsageDashboard} from '@/src/features/model-usage/public'")
    expect(settingsSections).toContain("v-show=\"props.activeSection === 'settings-model-usage'\"")
    expect(settingsSections).toContain(":active=\"props.activeSection === 'settings-model-usage'\"")
    expect(modelUsagePublic).toContain("from './ui/ModelUsageDashboard.vue'")
    expect(modelUsageDashboard).toContain('id="settings-model-usage"')
    expect(modelUsageDashboard).toContain("type: 'modelUsage'")
    expect(modelUsageDashboard).toContain("action: 'query'")
    expect(modelUsageDashboard).toContain("action: 'list'")
    expect(modelUsageDashboard).not.toContain("action: 'export'")
    expect(modelUsageDashboard).not.toContain("action: 'import'")
    expect(modelUsageDashboard).toContain("action: 'reset'")
    expect(modelUsageDashboard).toContain('完整备份与恢复统一在“备份与恢复”中管理')
    expect(modelUsageDashboard).not.toContain('导出全部数据')
    expect(modelUsageDashboard).not.toContain('导入模型用量数据')
    expect(modelUsageDashboard).not.toContain('type="file"')
    expect(modelUsageDashboard).toContain('<style scoped src="./model-usage-dashboard.css"></style>')
    expect(modelUsageDashboard).toContain('snapshot.value?.selected.filter')
    expect(modelUsageDashboard).toContain('{{ appliedRangeLabel }} · {{ appliedScopeLabel }}')
    expect(modelUsageDashboard).toContain('<em v-if="loading">正在更新…</em>')
    expect(modelUsageDashboard).toContain('<el-select v-model="selectedService"')
    expect(modelUsageDashboard).toContain('averageUncachedInputTokensPerCacheReportedRequest')
    expect(modelUsageDashboard).toContain('averageCachedInputTokensPerCacheReportedRequest')
    expect(modelUsageDashboard).toContain('averageOutputTokensPerCacheReportedRequest')
    expect(modelUsageDashboard).toContain('输入（无缓存）')
    expect(modelUsageDashboard).toContain('<em><span>占比</span> {{ formatUsageRate(selectedTotals.cachedInputTokenShare) }}</em>')
    expect(modelUsageDashboard).toContain('usage-average-grid')
    expect(modelUsageDashboard).toContain('按${option.label}排序')
    expect(modelUsageDashboard).toContain("{key: 'requests', label: '次数'}")
    expect(modelUsageDashboard).toContain("{key: 'cache', label: '缓存'}")
    expect(modelUsageDashboard).toContain('usage-breakdown-requests')
    expect(modelUsageDashboard).toContain('usage-breakdown-total')
    expect(modelUsageDashboard).toContain(':class="{ active: appliedFilter.serviceId === row.serviceId && appliedFilter.model === row.model }"')
    expect(modelUsageDashboard).toContain('if (totalTokens <= 0) return 0')
    expect(modelUsageDashboard).not.toContain('<span>模型缓存</span>')
    expect(modelUsageDashboard).not.toContain('缓存明细覆盖')
    expect(modelUsageDashboard).toContain('次{{ selectedTotals.cacheReportedRequests < selectedTotals.reportedTokenRequests ? \'可计算\' : \'\' }}请求命中')
    expect(modelUsageDashboard).toContain('逐请求可观测记录')
    expect(modelUsageDashboard).toContain('输入命中率 ${formatUsageRate(requestCacheRate(item))}')
    expect(modelUsageDashboard).toContain('缓存创建（服务商上报）')
    expect(modelUsageDashboard).toContain('requestPageSizeOptions')
    expect(modelUsageDashboard).toContain('第 {{ requestPageIndex + 1 }} / {{ requestPageCount }} 页')
    expect(modelUsageDashboard).toContain('loadNextRequestPage')
    expect(modelUsageDashboard).toContain('@click="loadRequestPage(requestLogRetryPageIndex)"')
    expect(modelUsageDashboard).toContain('requestLogRetryPageIndex.value = pageIndex')
    expect(modelUsageDashboard).toContain('if (pageIndex === 0) requestLogTotalCount.value = response.data.totalCount')
    expect(modelUsageDashboard).toContain('不保存原文、译文、提示词、网页地址、API Key、请求体或响应正文')
    expect(modelUsageDashboard).not.toContain('MODEL_USAGE_TRANSFER_FORMAT')
    expect(modelUsageDashboard).toContain('handleRangeKeydown')
    expect(modelUsageDashboard).toContain(':tabindex="range === option.value ? 0 : -1"')
    expect(modelUsageDashboard).toContain("if (event.key === 'Home') nextIndex = 0")
    expect(modelUsageDashboard).toContain('<Teleport to="body">')
    expect(modelUsageDashboard).toContain('ref="resetCancelButton"')
    expect(modelUsageDashboard).toContain("settingsApp?.setAttribute('inert', '')")
    expect(modelUsageDashboard).toContain("querySelectorAll<HTMLButtonElement>('button:not(:disabled)')")
    expect(modelUsageDashboard).toContain("document.addEventListener('visibilitychange', handleVisibilityChange)")
    expect(modelUsageDashboard).toContain("watch(() => props.active")
    expect(settingsSections).toContain('id="settings-translation"')
    expect(settingsSections).not.toContain('id="settings-webpage"')
    expect(settingsSections).not.toContain('id="settings-shortcuts"')
    expect(settingsSections).toContain('<ConfigManagement')
    expect(settingsSections).toContain('<SettingsGroup')
    expect(settingsSections).toContain("import QuickTranslationProfiles from './QuickTranslationProfiles.vue'")
    expect(quickTranslationProfiles).toContain("type QuickTranslationProfile")
    expect(quickTranslationProfiles).toContain('MAX_QUICK_TRANSLATION_PROFILES')
    expect(quickTranslationProfiles).toContain('CustomHotkeyInput')
    expect(quickTranslationProfiles).toContain('withCustomOpenAIServiceOptions')
    expect(quickTranslationProfiles).toContain('@media (max-width: 640px)')
    expect(quickTranslationProfiles).toContain('const creatingProfile = ref(false)')
    expect(quickTranslationProfiles).toContain('@click="addProfile($event)"')
    expect(quickTranslationProfiles).toContain(':validate="validateProfileHotkey"')
    expect(quickTranslationProfiles).not.toContain('class="empty-state"')
    expect(quickTranslationProfiles).not.toContain(':disabled="!profile.service"')
    expect(quickTranslationProfiles).toContain(":placeholder=\"t('quickTranslation.followDefault', {value: languageLabel(config.to)})\"")
    expect(quickTranslationProfiles).toContain('const {language, t, translateLegacy} = useUiI18n()')
    expect(translationShortcutSettings).toContain("t('quickTranslation.conflictProfile', {group})")
    expect(customHotkeyInput).toContain("if (event.key === 'Escape')")
    expect(customHotkeyInput.indexOf("if (event.key === 'Escape')"))
      .toBeLessThan(customHotkeyInput.indexOf('if (!isRecording.value) return;'))
    expect(customHotkeyInput).toContain("watch(dialogVisible, (visible) => {")
    expect(customHotkeyInput).toContain("currentHotkey.value = props.currentValue || '';")
    expect(customHotkeyInput).toContain('pressedKeys.value.clear();')
    expect(customHotkeyInput).toContain('validate?: (hotkey: string) => string;')
    expect(customHotkeyInput).toContain("const contextualError = props.validate?.(hotkeyString) || '';")
    expect(customHotkeyInput).not.toContain("emit('confirm', currentHotkey.value);\n  emit('update:modelValue', false);")
    expect(customHotkeyInput).toContain('!focusable.includes(activeElement)')
    expect(customHotkeyInput).toContain('(event.shiftKey ? last : first).focus();')
    expect(settingsSections).toContain(':validate="validateCustomFullPageHotkey"')
    expect(settingsSections).toContain(':validate="validateCustomMouseHotkey"')
    expect(settingsSections).toContain('quickTranslationConflictMessage')
    expect(settingsSections).toContain("quickTranslationConflictMessage('Shift+Z')")
    expect(settingsSections).toContain("useTranslationShortcutSettings(config)")
    expect(translationShortcutSettings).toContain('inputBoxTranslationTriggerHotkey(value)')
    expect(quickTranslationProfiles).toContain('inputBoxTranslationTriggerHotkey(props.config.inputBoxTranslationTrigger)')
    expect(translationShortcutSettings).toContain('previousFullPageHotkey')
    expect(translationShortcutSettings).toContain('previousSelectionTrigger')
    expect(configManagement).toContain('<LocalDataManagement :config="config" />')
    expect(configManagement.indexOf('<LocalDataManagement :config="config" />'))
      .toBeLessThan(configManagement.indexOf('<header class="history-heading">'))
    expect(configManagement).toContain('<h2>设置历史</h2>')
    expect(configManagement).toContain('<h2 id="automatic-backup-title">自动设置快照</h2>')
    expect(configManagement).not.toContain('仅迁移配置')
    expect(configManagement).not.toContain('config-transfer-dialog')
    expect(configManagement).not.toContain('openExportDialog')
    const transferActions = localDataManagement.match(/<div class="transfer-actions">([\s\S]*?)<\/div>/u)?.[1]
    expect(transferActions).toBeDefined()
    expect(transferActions?.match(/<el-button\b/gu)).toHaveLength(2)
    expect(transferActions).toContain('>导出备份</el-button>')
    expect(transferActions).toContain('>从备份恢复</el-button>')
    expect(configManagement).not.toContain('prepareConfigForExport(props.config)')
    expect(configManagement).not.toContain('persist-credentials-switch')
    expect(configManagement).not.toContain('跨浏览器重启保存 API 凭据')
    expect(configManagement).not.toContain('<SettingsGroup title="凭据安全"')
    expect(configManagement).not.toContain('type="file"')
    expect(configManagement).not.toContain('downloadConfig')
    expect(localDataManagement).toContain('title="完整备份"')
    expect(localDataManagement).not.toContain('分别管理')
    expect(localDataManagement).toContain('createFluentReadDataBackup')
    expect(localDataManagement).toContain('openRestoreSource($event)')
    expect(localDataManagement).toContain('data-testid="restore-source-dialog"')
    expect(localDataManagement).toContain('粘贴旧版配置 JSON')
    expect(localDataManagement).toContain('previewPastedImport')
    expect(localDataManagement).toContain('@click="exportCompleteBackup($event)"')
    expect(localDataManagement).toContain('@click="chooseImport($event)"')
    expect(localDataManagement).toContain('@click="previewPastedImport($event)"')
    expect(localDataManagement).toContain('await focusTriggerAfterBusy(trigger)')
    expect(localDataManagement).toContain('restoreSourceVisible.value && !importPreviewVisible.value')
    expect(localDataManagement).toContain('activeElement === document.body || activeElement === document.documentElement')
    expect(localDataManagement).toContain('chooseBackupContext')
    expect(localDataManagement).toContain("confirmButtonText: '不包含并导出'")
    expect(localDataManagement).toContain('prepareHydratedConfigForExport()')
    expect(localDataManagement).toContain('credentialMode: resolveBackupConfigCredentialMode(target.backup)')
    expect(localDataManagement).toContain("credentialIntent: target.kind === 'complete' && usesExactCredentialReplacement(target.backup)")
    expect(localDataManagement).toContain("? 'exact'")
    expect(localDataManagement).toContain(": 'changed-fields'")
    expect(localDataManagement).toContain('computed(() => prepareImportedConfig(pendingImport.value, props.config))')
    expect(localDataManagement).toContain('const targetConfig = prepareImportedConfig(target, props.config)')
    expect(localDataManagement).toContain("target?.kind === 'config'")
    expect(localDataManagement).not.toContain('dataset-row')
    expect(localDataManagement).not.toContain('按事件 ID')
    expect(localDataManagement).not.toContain('三个独立数据库')
    expect(serviceConfiguration).toContain('修改会自动保存；凭据只保存在当前设备')
    expect(serviceConfiguration).toContain('class="connection-field credential-field"')
    expect(serviceConfiguration).not.toContain('class="credential-warning"')
    expect(serviceConfiguration).not.toContain('默认仅保留在当前浏览器会话')
    expect(settingsSections).not.toContain('fluentReadImageOcrDownload')
    expect(settingsSections).toContain('普通文本 input、textarea 与 plaintext-only 编辑区')
    expect(settingsSections).toContain('密码框和富文本编辑器不参与')
    expect(settingsSections).not.toContain('任何文本输入框')
    expect(imagePublic).toContain("from './ui/ImageOcrSettings.vue'")
    expect(imageSettings).toContain('当前浏览器暂不支持图片翻译与 OCR')
    expect(imageSettings).toContain("type: 'fluentReadImageOcrDownload'")
    expect(imageSettings).toContain('<style scoped src="./image-ocr-settings.css"></style>')
    expect(popup).toContain('@/src/ui/components/CustomHotkeyInput.vue')
    expect(popup).toContain('@/src/ui/components/ServiceIcon.vue')
    expect(popup).toContain('@/src/platform/browser/ids')
    expect(popup).toContain('requestConfigPatch')
    expect(popup).toContain('requestConfigSave')
    expect(popup).toContain('config.interfaceVisibility.popupQuickFeatures')
    expect(popup).toContain('config.value.interfaceVisibility.popupSiteRule')
    expect(popup).toContain('config.interfaceVisibility.popupFooter')
    expect(popup).toContain('v-for="moduleId in visiblePopupModuleOrder"')
    expect(popup).toContain('config.value.popupModuleOrder.filter')
    expect(popup).toContain('config.value.popupQuickFeatureOrder.filter')
    expect(popup).toContain('config.value.popupQuickFeatureVisibility[featureId]')
    expect(popup).toContain('v-for="feature in visiblePopupQuickFeatures"')
    expect(popup).toContain(':data-popup-quick-feature="feature.id"')
    expect(popup).toContain('Record<PopupQuickFeatureId, PopupQuickFeatureViewModel>')
    expect(popup).toContain('data-popup-module="translation"')
    expect(popup).toContain('data-popup-module="quickFeatures"')
    expect(popup).toContain('data-popup-module="footer"')
    expect(popup).toContain('siteModuleNestedInTranslation')
    expect(popup).toContain(':data-popup-module-last="lastVisiblePopupModule === \'footer\'"')
    expect(popup).toContain("import PopupSiteRule from './PopupSiteRule.vue'")
    expect(popupStyles).toContain('.popup-content > [data-popup-module] + .hero-card')
    expect(popupStyles).toContain('footer[data-popup-module-last="false"]')
    expect(minimalSkinStyles).toContain('.popup-content > footer[data-popup-module-last="true"]')
    expect(popup).toContain('popupUsesContentHeight')
    expect(popup).toContain('interfaceSkinUsesContentHeight(config.value.interfaceSkin)')
    expect(popup).not.toContain("config.value.interfaceSkin === 'minimal'")
    expect(popup).toContain('dataset.popupHeight')
    expect(popup).toContain('applyInterfaceSkin')
    expect(popup).not.toMatch(/\bsaveConfig\b/u)
    expect(popup).not.toMatch(/(?:!tab\?\.id|filter\(tab\s*=>\s*tab\.id\))/u)
    expect(settingsSections).toContain('@/src/platform/browser/ids')
    expect(settingsSections).not.toMatch(/if\s*\(\s*!?tab\.id\s*\)/u)
  })

  it('keeps the Firefox persistence fixture aligned with the current data-section contract', () => {
    const firefoxPersistence = source('scripts/run-firefox-config-persistence.mjs')

    expect(firefoxPersistence).toContain('button[data-section="settings-data"]')
    expect(firefoxPersistence).toContain('备份与恢复导航不存在')
    expect(firefoxPersistence).toContain('result.historyCases.count > 10')
    expect(firefoxPersistence).not.toContain("textContent?.includes('配置管理')")
    expect(firefoxPersistence).not.toContain('配置管理导航不存在')
    expect(firefoxPersistence).not.toContain('result.historyCases.count > 5')
  })

  it('filters Chrome-only providers in every options selector without overwriting old values', () => {
    const settings = source('src/features/settings/ui/SettingsSections.vue')
    const document = source('src/app/document-translation/DocumentApp.vue')
    const translationCenter = source('src/features/translation-center/ui/TranslationCenter.vue')

    expect(settings).toContain('withCustomOpenAIServiceOptions(')
    expect(settings).toContain('filterAvailableTranslationServices(serviceOptionsWithCustomProviders.value)')
    expect(settings).toContain('selectedTextServiceUnavailableMessage')
    expect(settings).toContain('selectedVideoServiceUnavailableMessage')
    expect(settings).toContain('Chrome内置AI翻译（当前浏览器不可用）')
    expect(document).toContain('filterAvailableTranslationServices(withCustomOpenAIServiceOptions(')
    expect(document).toContain('config.customOpenAIProviders')
    expect(document).toContain('requestConfigPatch')
    expect(document).toContain('subscribeConfig')
    expect(document).not.toMatch(/\bsaveConfig\b/u)
    expect(document).toContain('documentServiceUnavailableMessage')
    expect(translationCenter).toContain('filterAvailableTranslationServices(withCustomOpenAIServiceOptions(')
    expect(translationCenter).toContain('getCustomOpenAIProviderModels(customOpenAIProviders.value')
    expect(translationCenter).toContain('原配置会保留')
    expect(translationCenter).toContain('if (!isTranslationServiceAvailable(service)) return [service]')
  })

  it('uses saved dynamic service profiles across document, comparison, history, usage and shared icons', () => {
    const document = source('src/app/document-translation/DocumentApp.vue')
    const translationCenter = source('src/features/translation-center/ui/TranslationCenter.vue')
    const configManagement = source('src/features/settings/ui/ConfigManagement.vue')
    const modelUsageDashboard = source('src/features/model-usage/ui/ModelUsageDashboard.vue')
    const serviceIcon = source('src/ui/components/ServiceIcon.vue')

    expect(document).toContain('return selectedCustomOpenAIProvider.value.models')
    expect(document).toContain('config.customModels[config.documentService]')
    expect(document).toContain('管理模型 ↗')
    expect(document).not.toContain('aria-label="文档自定义模型名称"')
    expect(document).toContain("'这个自定义服务尚未保存模型，请先前往服务设置添加模型。'")
    expect(translationCenter).toContain('isConfiguredCustomOpenAIProvider(customOpenAIProviders.value, item.value)')
    expect(configManagement).toContain('getCustomOpenAIProviderLabel(value.customOpenAIProviders, value.service)')
    expect(modelUsageDashboard).toContain('getCustomOpenAIProviderLabel(customOpenAIProviders.value, serviceId)')
    expect(modelUsageDashboard).toContain('const unsubscribeConfig = subscribeConfig(nextConfig =>')
    expect(serviceIcon).toContain('isCustomOpenAIProviderId(props.service)')
    expect(serviceIcon).toContain('v-else-if="isCustomOpenAIService"')
  })

  it('keeps dynamic OpenAI-compatible profiles editable in userscript settings', () => {
    const userscriptSettings = source('userscript/SettingsPanel.vue')

    expect(userscriptSettings).toContain('withCustomOpenAIServiceOptions(')
    expect(userscriptSettings).toContain('draft.value.customOpenAIProviders')
    expect(userscriptSettings).toContain('selectedCustomOpenAIProvider.value?.models')
    expect(userscriptSettings).toContain('isCustomOpenAIService.value || servicesType.isUseModel')
    expect(userscriptSettings).toContain('v-model.trim="customOpenAIEndpoint"')
    expect(userscriptSettings).toContain('provider.id === service ? {...provider, endpoint} : provider')
    expect(userscriptSettings).toContain('if (service === services.custom) draft.value.custom = endpoint')
    expect(userscriptSettings).toContain('draft.value.customModels[service] = normalizeCustomOpenAIModels')
    expect(userscriptSettings).toContain('function removeSelectedCustomModel()')
    expect(userscriptSettings).toContain('删除当前自定义模型')
    expect(userscriptSettings).not.toContain('v-model.trim="draft.custom" inputmode="url"')
    const serviceFieldsetStart = userscriptSettings.indexOf('<legend>翻译服务</legend>')
    const serviceFieldsetEnd = userscriptSettings.indexOf('</fieldset>', serviceFieldsetStart)
    const serviceFieldsetSource = userscriptSettings.slice(serviceFieldsetStart, serviceFieldsetEnd)
    const advancedRequestStart = userscriptSettings.indexOf('<summary>高级 AI 请求设置</summary>')
    const advancedRequestEnd = userscriptSettings.indexOf('</details>', advancedRequestStart)
    const advancedRequestSource = userscriptSettings.slice(advancedRequestStart, advancedRequestEnd)
    expect(serviceFieldsetStart).toBeGreaterThanOrEqual(0)
    expect(serviceFieldsetEnd).toBeGreaterThan(serviceFieldsetStart)
    expect(serviceFieldsetSource).not.toContain('Thinking')
    expect(advancedRequestStart).toBeGreaterThanOrEqual(0)
    expect(advancedRequestEnd).toBeGreaterThan(advancedRequestStart)
    expect(advancedRequestSource).toContain('aria-label="当前模型是否启用 Thinking"')
    expect(advancedRequestSource).toContain('v-model="selectedModelThinking"')
    expect(userscriptSettings).not.toContain('customModelThinking')
  })

  it('offers selectable paragraph loading animations with true runtime previews', () => {
    const settings = source('src/features/settings/ui/SettingsSections.vue')
    const picker = source('src/features/settings/ui/TranslationLoadingStyleSettings.vue')
    const preview = source('src/ui/components/TranslationLoadingPreview.vue')
    const indicator = source('src/ui/translationLoadingIndicator.ts')
    const pageStyles = source('src/app/content/page.css')
    const userscriptSettings = source('userscript/SettingsPanel.vue')
    const userscriptSmoke = source('scripts/run-userscript-smoke-test.cjs')

    expect(settings).toContain('<TranslationLoadingStyleSettings :config="config" />')
    expect(picker).toContain('v-for="option in translationLoadingStyleOptions"')
    expect(picker).toContain('role="radiogroup"')
    expect(picker).toContain('<TranslationLoadingPreview')
    expect(picker).toContain(':animated="props.config.animations"')
    expect(picker).toContain("import { useUiI18n } from '@/src/ui/i18n'")
    expect(picker).toContain('const { t } = useUiI18n()')
    expect(picker).toContain('t(option.labelKey)')
    expect(picker).toContain('t(option.descriptionKey)')
    expect(picker).not.toContain('{{ option.label }}')
    expect(picker).not.toContain('{{ option.description }}')
    expect(preview).toContain('createTranslationLoadingIndicator(document')
    expect(indicator).toContain("attachShadow({mode: 'closed'})")
    expect(indicator).toContain("['animation', 'none']")
    expect(indicator).toContain("['all', 'initial']")
    expect(indicator).toContain(':host::before')
    expect(indicator).toContain('content: none !important')
    expect(indicator).not.toContain("classList.add('static')")
    expect(pageStyles).not.toMatch(/@keyframes\s+spin\b/u)
    expect(userscriptSettings).toContain('v-model="draft.translationLoadingStyle"')
    expect(userscriptSettings).toContain(':disabled="!draft.animations"')
    expect(userscriptSettings).toContain('<TranslationLoadingPreview :loading-style="draft.translationLoadingStyle"')
    expect(userscriptSettings).toContain('aria-label="当前动画参考"')
    expect(userscriptSmoke).toContain("translationLoadingStyle: 'orbit'")
    expect(userscriptSmoke).toContain('userscriptLoadingStyle')
    expect(userscriptSmoke).toContain('HOST PAGE')
  })

  it('persists document and translation-center edits as precise field patches', () => {
    const document = source('src/app/document-translation/DocumentApp.vue')
    const translationCenter = source('src/features/translation-center/ui/TranslationCenter.vue')

    expect(document).toContain('const patch: DocumentConfigPatch = {}')
    expect(document).toContain('if (value.from !== previous.from) patch.from = value.from')
    expect(document).toContain('if (value.documentService !== previous.documentService)')
    expect(document).toContain('mergeChangedDocumentModelMapping(')
    expect(document).toContain('runtimeConfig.documentModel')
    expect(document).toContain('runtimeConfig.documentCustomModel')
    expect(document).not.toContain('documentModel: value.documentModel')
    expect(document).not.toContain('documentCustomModel: value.documentCustomModel')
    expect(document).toContain('config.documentModel[service] = value')
    expect(document).toContain('config.documentCustomModel[service] = value')
    expect(document).toContain('config.documentModel[service] = customModelString')
    expect(document).toContain("{deep: true, flush: 'post'}")

    expect(translationCenter).toContain("persistTranslationCenterConfig('source')")
    expect(translationCenter).toContain("persistTranslationCenterConfig('target')")
    expect(translationCenter).toContain("persistTranslationCenterConfig('services')")
    expect(translationCenter).toContain("persistTranslationCenterConfig('source', 'target')")
    expect(translationCenter).toContain('const requestedFields = new Set(fields)')
    expect(translationCenter).toContain('if (Object.keys(patch).length === 0) return')
  })

  it('uses patches for ordinary autosaves while retaining a best-effort page-exit snapshot', () => {
    const popup = source('src/app/popup/PopupApp.vue')
    const settings = source('src/features/settings/ui/SettingsSections.vue')

    for (const content of [popup, settings]) {
      expect(content).toContain('requestConfigPatch')
      expect(content).toContain('requestConfigSave')
      expect(content).toContain('persistConfigPatch(snapshot)')
      expect(content).toContain('persistConfigReplace(config.value)')
      expect(content).toContain('best-effort')
      expect(content).toContain('revision 边界会拒绝过期 replace')
      expect(content).not.toContain('replace 作为队列 flush/barrier')
    }
  })

  it('persists before remote tests while starting Chrome model preparation inside click activation', () => {
    const serviceConfiguration = source('src/features/settings/ui/services/ServiceConfiguration.vue')
    const testConnectionStart = serviceConfiguration.indexOf('async function testConnection(): Promise<void>')
    const testConnectionEnd = serviceConfiguration.indexOf('function resetCustomTemplate(): void', testConnectionStart)
    const testConnection = serviceConfiguration.slice(testConnectionStart, testConnectionEnd)
    const chromePreparationIndex = testConnection.indexOf('prepareChromeTranslationInPage({')
    const waitIndex = testConnection.indexOf('await waitForConfigPersistenceQueue()')
    const saveIndex = testConnection.indexOf('await requestConfigSave(config.value')
    const connectionTestIndex = testConnection.indexOf('type: CONNECTION_TEST_MESSAGE')

    expect(testConnectionStart).toBeGreaterThanOrEqual(0)
    expect(testConnectionEnd).toBeGreaterThan(testConnectionStart)
    expect(chromePreparationIndex).toBeGreaterThanOrEqual(0)
    expect(chromePreparationIndex).toBeLessThan(waitIndex)
    expect(waitIndex).toBeGreaterThanOrEqual(0)
    expect(saveIndex).toBeGreaterThan(waitIndex)
    expect(connectionTestIndex).toBeGreaterThan(saveIndex)
    expect(testConnection).toContain('testedService === services.chromeTranslator')
    expect(testConnection).toContain('if (chromePreparation)')
    expect(testConnection).toContain('service: testedService')
  })

  it('labels Chrome connection action as preparation for only the displayed language pair', () => {
    const serviceConfiguration = source('src/features/settings/ui/services/ServiceConfiguration.vue')
    const chromePreparation = source('src/features/settings/model/chromeTranslationPreparation.ts')

    expect(serviceConfiguration).toContain("t('settings.services.chromePreparation.action')")
    expect(serviceConfiguration).toContain("t('settings.services.chromePreparation.titleReady')")
    expect(serviceConfiguration).toContain("t('settings.services.chromePreparation.noKey')")
    expect(serviceConfiguration).toContain('const { language, t } = useUiI18n()')
    expect(serviceConfiguration).toContain('data-chrome-preparation-source')
    expect(serviceConfiguration).toContain('data-i18n-ignore')
    expect(serviceConfiguration).toContain('getChromeTranslationPreparationLanguageLabel(item.value, language)')
    expect(serviceConfiguration).toContain('from: chromePreparationSourceLanguage.value')
    expect(serviceConfiguration).toContain("t('settings.services.chromePreparation.sourceDescription')")
    expect(serviceConfiguration).toContain('CHROME_PREPARATION_TIMEOUT_MS = 300_000')
    expect(serviceConfiguration).toContain('activeChromePreparation?.abort()')
    expect(serviceConfiguration).toContain("'settings.services.chromePreparation.success'")
    expect(serviceConfiguration).toContain('ChromeTranslationPreparationError')
    expect(serviceConfiguration).toContain('CHROME_PREPARATION_ERROR_KEYS[error.code]')
    expect(serviceConfiguration).not.toContain('Chrome 本地翻译已全部准备')
    expect(chromePreparation).toContain('再次点击“准备 Chrome 本地翻译”继续准备')
    expect(chromePreparation).toContain("'user-activation-required'")
  })

  it('uses bounded model picking and atomic custom-service drafts in settings', () => {
    const settings = source('src/features/settings/ui/SettingsSections.vue')
    const catalog = source('src/features/settings/ui/services/ServiceCatalog.vue')
    const modelPicker = source('src/features/settings/ui/services/ModelPicker.vue')
    const providerDialog = source('src/features/settings/ui/services/CustomOpenAIProviderDialog.vue')
    const serviceConfiguration = source('src/features/settings/ui/services/ServiceConfiguration.vue')
    const promptEditor = source('src/features/settings/ui/services/PromptTemplateEditor.vue')

    expect(catalog).toContain('data-testid="custom-service-add"')
    expect(catalog).toContain('我的服务')
    expect(catalog).toContain('<ModelPicker')
    expect(catalog).not.toContain('model-grid expanded')
    expect(catalog).not.toContain('.model-grid.expanded')
    expect(modelPicker).toContain('popper-class="model-picker-popper"')
    expect(modelPicker).toContain('transition="model-picker-instant"')
    expect(modelPicker).toContain("import {ElPopover} from 'element-plus'")
    expect(modelPicker).toContain('<ElPopover')
    expect(modelPicker).toContain(':key="pickerContentKey"')
    expect(modelPicker).toContain('const pickerContentKey = computed(')
    expect(modelPicker).toContain('max-height: min(240px, 40vh)')
    expect(modelPicker).toContain('class="model-picker-chip"')
    expect(modelPicker).toContain('pickerTrigger.value?.focus({preventScroll: true})')
    const removeModelStart = modelPicker.indexOf('function removeModel(model: string): void')
    const removeModelEnd = modelPicker.indexOf('\n}', removeModelStart)
    const removeModelSource = modelPicker.slice(removeModelStart, removeModelEnd)
    expect(removeModelSource).toContain("emit('remove', model)")
    expect(removeModelSource).toContain('closePicker()')
    expect(removeModelSource.indexOf('closePicker()'))
      .toBeLessThan(removeModelSource.indexOf("emit('remove', model)"))
    expect(modelPicker).toContain('@click.stop="removeModel(option.value)"')
    expect(modelPicker).toContain('opacity: 1 !important')
    expect(modelPicker).toContain('data-testid="custom-model-input"')
    expect(modelPicker).not.toContain('data-testid="custom-model-thinking"')
    expect(modelPicker).toContain("emit('add', model)")
    expect(modelPicker).not.toContain('Thinking')
    expect(catalog).not.toContain('data-testid="model-thinking-control"')
    expect(catalog).not.toContain('Thinking')
    const advancedSettingsStart = serviceConfiguration.indexOf(
      '<details v-if="compute.showAI" class="custom-advanced-settings"',
    )
    const advancedSettingsEnd = serviceConfiguration.indexOf('</details>', advancedSettingsStart)
    const advancedSettingsSource = serviceConfiguration.slice(advancedSettingsStart, advancedSettingsEnd)
    expect(advancedSettingsStart).toBeGreaterThanOrEqual(0)
    expect(advancedSettingsEnd).toBeGreaterThan(advancedSettingsStart)
    expect(advancedSettingsSource).toContain('data-testid="model-thinking-control"')
    expect(advancedSettingsSource).toContain(':model-value="selectedModelThinking"')
    expect(advancedSettingsSource).toContain("$emit('update:model-thinking', Boolean($event))")
    expect(modelPicker).toContain('model === CUSTOM_OPENAI_RESERVED_MODEL_ID')
    expect(providerDialog).toContain('data-testid="custom-service-dialog"')
    expect(providerDialog).not.toContain('data-testid="custom-service-model-thinking"')
    expect(providerDialog).not.toContain('Thinking')
    expect(providerDialog).toContain('const draft = reactive<CustomOpenAIProviderDraft>')
    expect(providerDialog).toContain("emit('submit', value)")
    expect(providerDialog).toContain('value.model === CUSTOM_OPENAI_RESERVED_MODEL_ID')
    expect(settings).toContain('createNextCustomOpenAIProviderId(')
    expect(settings).toContain('configurationService.value = id')
    expect(settings).toContain('configurationService.value = null')
    expect(settings).toContain('!getCustomOpenAIProvider(config.value.customOpenAIProviders, service)')
    expect(settings).toContain('removeCustomOpenAIProvider(')
    expect(settings).toContain('updateConfigAtomically((next) =>')
    expect(settings).toContain(':selected-model-thinking="selectedConfigurationModelThinking"')
    expect(settings).toContain('@update:model-thinking="updateSelectedConfigurationModelThinking"')
    expect(settings).toContain('withoutModelThinkingPreference(next.modelThinking, service, model)')
    expect(serviceConfiguration).not.toContain('v-model="config.customModel[service]"')
    expect(serviceConfiguration).not.toContain('v-show="compute.')
    expect(serviceConfiguration).toContain('v-if="compute.showMiniMaxRegion"')
    expect(serviceConfiguration).toContain('width: 100% !important; max-width: none !important;')
    expect(serviceConfiguration).toContain('data-testid="custom-service-advanced"')
    expect(serviceConfiguration).toContain('v-if="compute.showAI" class="custom-advanced-settings"')
    expect(serviceConfiguration).toContain('<PromptTemplateEditor v-model="config.system_role[service]" role="system" />')
    expect(serviceConfiguration).toContain('<PromptTemplateEditor v-model="config.user_role[service]" role="user" />')
    expect(promptEditor).toContain('data-prompt-token')
    expect(promptEditor).toContain("{value: '{{to}}', label: '目标语言'}")
    expect(promptEditor).toContain("{value: '{{origin}}', label: '待翻译原文'}")
    expect(promptEditor).toContain('v-if="promptTokens.length"')
    expect(promptEditor).toContain("props.role === 'user'")
    expect(promptEditor).toContain('@mousedown.prevent')
  })

  it('puts service selection, webpage assistance and translated-text display in General', () => {
    const settings = source('src/features/settings/ui/SettingsSections.vue')
    const general = activeSectionSource(settings, 'settings-general')
    const services = activeSectionSource(settings, 'settings-services')
    const styles = sourceBody('src/features/settings/ui/settings-sections.css')

    expect(settingsGroupTitles(general)).toEqual(['选择翻译服务', '译文显示', '网页辅助'])
    expect(general).toContain('data-testid="default-translation-service-card"')
    expect(general).toContain(':data-default-service="config.service"')
    expect(general).toContain('<SettingsItem label="默认网页翻译服务"')
    expect(general).toContain(":description=\"t('quickTranslation.defaultServiceDescription')\"")
    expect(general).not.toContain('description="全文、悬浮和划词翻译默认使用此服务。"')
    expect(general).not.toContain('全文、悬浮、划词和输入框翻译默认使用此服务')
    expect(general).toContain('<ServiceIcon :service="config.service" :label="defaultTextServiceLabel" size="medium"')
    expect(general).toContain('aria-label="默认网页翻译服务"')
    expect(general).toContain('defaultTextServiceLabel')
    expect(general).toContain('aria-label="AI 智能上下文"')
    const aiContextSwitch = general.match(/<el-switch\b[^>]*aria-label="AI 智能上下文"[^>]*\/>/u)?.[0]
    expect(aiContextSwitch).toBeDefined()
    expect(aiContextSwitch).not.toContain(':disabled')
    expect(general).toContain('label="翻译模式"')
    expect(general).toContain('aria-label="译文样式"')
    expect(general).toContain('v-model="config.bilingualSentenceHighlightEnabled"')
    expect(general).toContain(":label=\"t('settings.general.bilingualSentenceHighlight')\"")
    expect(general).toContain(":description=\"t('settings.general.bilingualSentenceHighlightDescription')\"")
    expect(general).toContain(":aria-label=\"t('settings.general.bilingualSentenceHighlight')\"")
    expect(general).toContain('data-testid="bilingual-highlight-preview"')
    expect(general).toContain('data-testid="bilingual-highlight-preview-source"')
    expect(general).toContain('data-testid="bilingual-highlight-preview-translation"')
    expect(general).toContain(':data-bilingual-highlight-enabled="String(config.bilingualSentenceHighlightEnabled)"')
    expect(general).toContain("'is-bilingual-highlight-enabled': config.bilingualSentenceHighlightEnabled")
    expect(styles).toContain('.bilingual-highlight-preview.is-bilingual-highlight-enabled:hover')
    expect(styles).toContain('.bilingual-highlight-preview.is-bilingual-highlight-enabled:focus-visible')
    expect(styles).toContain('.style-preview-text::before')

    expect(services).toContain('<ServiceCatalog')
    expect(services).not.toContain('data-testid="default-translation-service-card"')
    expect(services).not.toContain('aria-label="默认网页翻译服务"')
    expect(services).not.toContain('<SettingsGroup')
    expect(styles).toContain('.service-default-control')
    expect(styles).not.toContain('.service-default-status')
    expect(styles).not.toContain('.service-default-picker')
    expect(styles).not.toContain('box-shadow: inset 4px 0 0 var(--brand);')
  })

  it('keeps the service catalog hierarchy searchable and accessible', () => {
    const catalog = source('src/features/settings/ui/services/ServiceCatalog.vue')
    const viewModel = source('src/ui/view-model/serviceCatalog.ts')
    const serviceDescriptionStyles = catalog.match(/\.service-copy small \{([^}]*)\}/u)?.[1] || ''

    expect(catalog).toContain(':data-service-section-toggle="section.id"')
    expect(catalog).toContain(':aria-expanded="!isSectionCollapsed(section)"')
    expect(catalog).toContain(':aria-controls="`service-section-${section.id}`"')
    expect(catalog).toContain(':disabled="Boolean(serviceQuery)"')
    expect(catalog).toContain("serviceQuery ? '搜索中'")
    expect(catalog).toContain(':global(:root.dark .group-toggle-copy) { color: var(--brand-strong); }')
    expect(catalog).toContain("const collapsedSectionIds = ref(new Set(['machine']))")
    expect(catalog).toContain('&& !serviceQuery.value')
    expect(catalog).toContain('sectionContainsService(section, editingService)')
    expect(catalog).toContain('sectionContainsService(section, defaultService)')
    expect(viewModel).toContain("label: '模型服务商'")
    expect(viewModel).toContain("label: '聚合平台与接口'")
    expect(viewModel).toContain("item.catalogKind === 'platform'")
    expect(serviceDescriptionStyles).toContain('display: block')
    expect(serviceDescriptionStyles).toContain('min-width: 0')
    expect(serviceDescriptionStyles).toContain('overflow: hidden')
    expect(serviceDescriptionStyles).toContain('text-overflow: ellipsis')
    expect(serviceDescriptionStyles).toContain('white-space: nowrap')
  })

  it('keeps translation interactions together in the requested order', () => {
    const settings = source('src/features/settings/ui/SettingsSections.vue')
    const translation = activeSectionSource(settings, 'settings-translation')

    expect(settingsGroupTitles(translation)).toEqual([
      '鼠标悬浮翻译',
      '划词翻译',
      '输入框翻译',
      '全文翻译',
    ])
    expect(translation).toContain('aria-label="鼠标悬浮快捷键"')
    expect(translation).toContain('label="划词翻译模式"')
    expect(translation).toContain('aria-label="输入框翻译触发方式"')
    expect(translation).toContain('label="全文翻译范围"')
    expect(translation).toContain('aria-label="AI 多段翻译"')
    expect(translation).toContain('v-model="config.enableAIMultiSegment"')
    expect(translation.match(/<QuickTranslationProfiles\b/gu)).toHaveLength(2)
    expect(translation).toContain('action="hover"')
    expect(translation).toContain('action="full-page"')
    expect(translation.match(/:profiles="config\.quickTranslationProfiles"/gu)).toHaveLength(2)
    expect(translation.match(/@update:profiles="config\.quickTranslationProfiles = \$event"/gu)).toHaveLength(2)

    const hoverProfiles = translation.indexOf('action="hover"')
    const fullPageProfiles = translation.indexOf('action="full-page"')
    expect(hoverProfiles).toBeGreaterThan(translation.indexOf('aria-label="悬浮翻译延迟"'))
    expect(hoverProfiles).toBeLessThan(translation.indexOf('title="划词翻译"'))
    expect(fullPageProfiles).toBeGreaterThan(translation.indexOf('label="全文翻译范围"'))
    expect(fullPageProfiles).toBeGreaterThan(translation.indexOf('aria-label="右键全文翻译"'))
  })

  it('loads shared tokens before the unchanged settings page rules', () => {
    const pageStyles = sourceBody('src/features/settings/ui/settings-page.css')
    const tokens = source('src/ui/styles/tokens.css')

    expect(pageStyles.startsWith('@import "../../../ui/styles/tokens.css";')).toBe(true)
    expect(tokens).toContain('--fr-color-brand: #ef4776;')
    expect(tokens).toContain('--surface-soft: var(--fr-color-surface-soft);')
  })

  it('keeps bilingual sentence highlighting opt-in and scoped to bilingual wrappers', () => {
    const page = source('src/app/content/page.css')

    expect(page).toContain('html[data-fr-bilingual-sentence-highlight="true"] .fluent-read-bilingual:hover')
    expect(page).toContain('box-shadow: inset 0 0 0 1px rgba(239, 71, 118, 0.18) !important;')
    expect(page).toContain('.fluent-read-bilingual:hover > .fluent-read-bilingual-content::before')
    expect(page).toContain('background-color: rgba(239, 71, 118, 0.58);')
    expect(page).not.toContain('.fluent-read-bilingual-content {\n    background-color: rgba(239, 71, 118')
  })
})
